### ISSUE TITLE
Long animations can lead to invalid DOM state.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/animator-css#44]
http://plnkr.co/edit/LwzMIIeAOtI5V08CMTL3?p=preview

Click the `Toggle Condition` two times in quick succession (under 2 second), wait a couple second, then notice how both items go away, yet the `if.bind` on both clearly indicates that one should always be visible.

Including source code below in case the plunkr doesn't work at some point.  Leaving out JSPM boilerplate.

main.js
```js
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-animator-css');

  aurelia.start().then(a => a.setRoot());
}
```

app.js
```js
export class AnimationDemo{  
    conditition = true;
}
```

app.html
```html
<template>  
    <button click.delegate="condition = !condition">Toggle Condition</button>
    <div class="au-animate foo" if.bind="condition">foo</div>
    <div class="au-animate foo" if.bind="!condition">bar</div>
</template>  
```

styles.css
```css
.foo.au-enter {
    opacity: 0!important;
}

.foo.au-enter-active {
    -webkit-animation: fadeIn 2s;
    animation: fadeIn 2s;
}

.foo.au-leave-active {
    -webkit-animation: fadeOut 2s;
    animation: fadeOut 2s;
}

/* CSS3-Animations */
@-webkit-keyframes fadeIn {
    0%   { opacity: 0; }
    100% { opacity: 1; }
}

@keyframes fadeIn {
    0%   { opacity: 0; }
    100% { opacity: 1; }
}

@-webkit-keyframes fadeOut {
    0%   { opacity: 1; }
    100% { opacity: 0; }
}

@keyframes fadeOut {
    0%   { opacity: 1; }
    100% { opacity: 0; }
}
```

**Comment by EisenbergEffect** [comment]
@martingust I think this may be the same issue that we are trying to track down on the repeater...

**Comment by martingust** [comment]
@EisenbergEffect Just took a look at this and yes it's the same issue we had in the repeater. Will get a fix in for this.

**Comment by martingust** [comment]
@EisenbergEffect @Zoltu This issue is fixed with this [PR](https://github.com/aurelia/templating-resources/pull/202)

**Comment by erkalicious** [comment]
This issue still happens when `show.bind` and its animator classes are used as opposed to `if.bind`.
